# JDemetra+-Quickstart for the graphical user interface (GUI) { .unnumbered #quickstart}


The sections below will briefly describe the steps involved in installing JDemetra+, uploading the data, perform seasonal adjustment and export the data. The guide is intended for a novice user, hence it does not dwell on the theoretical aspects of seasonal adjustment. 

-   How to install JDemetra+

-   How to get data into JDemetra+

-   How to do seasonally adjust your data

-   How to export the data

## JDemetra+ installation

Easy breezy

### The structure of the software
At start-up of JDemetra+, the software loads the parts "Workspace" and "Providers". The latter includes multiple possibilities to load data into JDemetra+, most importantly loading spreadsheets (see below).

[Picture of default JD+ view]

The "Workspace" most importantly includes seasonal adjustment specificiations and results. For practical purposes, usually the "Seasonal adjustment" --> "multi-documents" section is most relevant. Here, multiple seasonal adjustment items can be placed. This means, that for each of multiple time series specifications can be defined, stored and used to compute the seasonally adjusted results.

[Picture of JD+ with opened multi-docs]

By right-clicking on an sa-item the user can select the base specification, most importantly, whether a Tramo-Seats or X-13 type adjustment should be applied.
By left-clicking on one sa-item, the method-specific specifications can be set. This includes the ARIMA model, outlier and calendar adjustment as well as details of the seasonal adjustment method.

[Picture of JD+ with specification]

DO WE WANT TO DISCUSS PLUG-INS HERE?

## Data import

From Excel


## Default seasonal adjustment

| Method      | Name in GUI   | Details                                                                                                                                              |
|-------------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| Tramo-Seats | tramoseats    | Decomposition of the time series based on RegARIMA modelling                                                                                         |
| X-13-ARIMA  | x13           | Combination of RegARIMA modelling for calendar effect and moving average based decomposition (X-11) for the extraction of the seasonal effect        |

Full documentation of the Seats method can be found [here](https://jdemetra-new-documentation.netlify.app/m-x11-decomposition), while all details on X-11 can be found [here](https://jdemetra-new-documentation.netlify.app/m-x11-decomposition).


## Export the data

To export the data you can choose xlsx, csv


